### ISSUE TITLE
第一次进入且无网络时闪退

### ISSUE THREAD

**Issue by 70kg** [ZhaoKaiQiang/JianDan#10]
当第一次安装，无网络连接时，闪退，空指针异常
![](https://github.com/70kg/Android-Studio-Project/blob/master/Screenshots/%E5%BC%82%E5%B8%B8.png)  
图片怎么显示不出来。。贴代码
java.lang.NullPointerException
            at com.socks.jiandan.ui.fragment.FreshNewsFragment$FreshNewsAdapter.onBindViewHolder(FreshNewsFragment.java:222)
            at com.socks.jiandan.ui.fragment.FreshNewsFragment$FreshNewsAdapter.onBindViewHolder(FreshNewsFragment.java:173)

**Comment by ZhaoKaiQiang** [comment]
请安装最新版本，再试一下，我这边测试没问题的，如果有BUG，请把所有打印信息粘贴
